version: "3.1"

services:
  visualizer:
    image: alexellis2/visualizer-arm:latest
    ports:
      - "80:8080/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role==manager
